### ISSUE TITLE
Project Timeline: indicate ongoing (from DOE comments)

### ISSUE THREAD

**Issue by Neil-Swanson** [mhk-env/mhk-env.github.io#10]
# Update project timeline to address DOE comments.
From [MHK Toolkit notes_DOE.docx - Google Docs:](https://docs.google.com/document/d/1yNnqEyZOBQdxYDTB0vDMymtitwW4YHRv/edit)

## Comment from DOE
> For projects that are ongoing (e.g. PacWave, WETS, Igiugig) the dates displayed goes through 12/31/20.  Would it be possible to change to “ongoing” or something like that?  Otherwise it might be misleading that the projects are slated to end by that date.

@bbest @geocoug: thoughts on having an end arrow on projects that are ongoing? Or perhaps adding an asterisk and footnote to the plot that indicates the projects are ongoing?

**Comment by bbest** [comment]
Figure in https://mhk-env.us/projects.html, generated by [projects.Rmd](https://github.com/mhk-env/mhk-env.github.io/blob/master/projects.Rmd):

![image](https://user-images.githubusercontent.com/2837257/104518140-1a5d7380-55ac-11eb-81f3-8665ae802a1d.png)

**Data**: [MHK Project Timeline Input - Google Sheets](https://docs.google.com/spreadsheets/d/1HC5hXyi2RQSHevnV7rvyk748U5-X3iUw70ewHEfrHm0/edit#gid=793817660)

We could have a few options based on scenario:

1. End date is known: solid gray
2. End date is vague: whiter gray
3. End date is unknown or ongoing (ie active): 
  1. asterisk *
  2. elipses ...

Different states:
- active
- cancelled
- ...

**Comment by bbest** [comment]
In **date_end** column of [MHK Project Timeline Input - Google Sheets](https://docs.google.com/spreadsheets/d/1HC5hXyi2RQSHevnV7rvyk748U5-X3iUw70ewHEfrHm0/edit#gid=793817660), @rupertsmudge suggested:

Changing these 12/31/2020 values to ACTIVE; then in Projects Timeline map and plot use today's date.
