### ISSUE TITLE
Update OpenEI verbiage to "Marine Energy"

### ISSUE THREAD

**Issue by geocoug** [mhk-env/mhk-env.github.io#12]
[MHK-env](https://openei.org/wiki/MHK-env)
- Convert MHK verbiage to Marine Energy
- Claim new wiki subpage
- Update toolkit links

**Comment by bbest** [comment]
Done me thinks, right @wjpepli? :)

**Comment by wjpepli** [comment]
Yep.

I need to look at the grammer though to make sure the sentence structure makes sense.

Will
