### ISSUE TITLE
Get Zach's web language integrated

### ISSUE THREAD

**Issue by bbest** [mhk-env/mhk-env.github.io#18]
---------- Forwarded message ---------
From: Zach Barr <zbarr@kearnswest.com>
Date: Mon, Jan 25, 2021 at 9:33 AM
Subject: Draft Marine Energy Website Language
To: Ben Best <ben@ecoquants.com>, Grace Chang <gchang@integral-corp.com>

Hi Ben and Grace, Please find attached an excel spreadsheet of draft language for the website. I’ve also uploaded it to the Google Drive here -https://docs.google.com/spreadsheets/d/1VlXnMPBFbeLaC-0fZvlBeIc2MS-2-bTh/edit#gid=933399346 Let me know if you have any questions or thoughts. I know there’s lots of stuff going on for the development of the Toolkit so let me know how I can help in anyway. Best,Zach

* [DRAFT_Website Language.xlsx - Google Sheets](https://docs.google.com/spreadsheets/d/1VlXnMPBFbeLaC-0fZvlBeIc2MS-2-bTh/edit#gid=933399346)

**Comment by bbest** [comment]
Hey @Neil-Swanson, the content here would be for either of the following:

- [index.html](https://github.com/mhk-env/mhk-env.github.io/blob/master/index.html): homepage
- *.Rmd -> *.html in [/](https://github.com/mhk-env/mhk-env.github.io)
- Shiny tabs: Configure, Literature, Spatial, Report in [mhk-env_shiny-apps: report/ui.R](https://github.com/mhk-env/mhk-env_shiny-apps/blob/master/report/ui.R). 
  - Open in rstudio.marineenergy.app `/share/github/mhk-env_shiny-apps_dev/mhk-env_shiny-apps.Rproj` on branch `lang-edits` to see dev in https://shiny.marineenergy.app/report-dev/. For example, see commit https://github.com/mhk-env/mhk-env_shiny-apps/commit/d0d13c2879c0234397b1399c8dc16f9c6cd97ab5.

**Comment by bbest** [comment]
Well done @Neil-Swanson with lang edits not only to website but now Shiny. To fully integrate from the lang-edits branch in https://github.com/mhk-env/mhk-env_shiny-apps the development environment ie mhk-env_shiny-apps_dev (https://shiny.marineenergy.app/report-dev/) to the production environment mhk-env_shiny-apps (https://shiny.marineenergy.app/report/), you'll want to do the following steps:

1. **Merge** the branch with the master in a pull request.
2. **Pull** the updated master branch on the server into mhk-env_shiny-apps.
3. **Touch** the restart.txt file in the report folder on the server to tell the Shiny server to reload the app. `touch report/restart.txt`

**Comment by Neil-Swanson** [comment]
All language added. Thanks @bbest !
