### ISSUE TITLE
add tutorial videos

### ISSUE THREAD

**Issue by bbest** [mhk-env/mhk-env.github.io#35]
- Github branch: [videos](https://github.com/marineenergy/www/tree/videos)
- OLD: FAQ [help.html](https://marineenergy.app/help.html)
- NEW: Frequently Asked Questions [faq.html](https://www-dev.marineenergy.app/faq.html)

NEW additions / changes:
- `vembeddr::embed_youtube()`
- floating table of contents (toc) to headers
- youtube icon prefixing headers with video
- renamed `help.html` -> `faq.html` and updated `_site.yaml` for navigation menu

![image](https://user-images.githubusercontent.com/2837257/153730435-2ef79c56-31e8-452a-b2be-9aaf8b7822e6.png)

**Comment by geocoug** [comment]
There are two more How-To videos to link to on the Toolkit FAQ page:
 
**Interactions** - Search scientific literature on the Tethys Knowledge Base and archive results.
https://youtu.be/dyBspq8Aveg
(Let’s place Interactions below Custom Reports)
 
**Management Measures Tool** - Explore a robust compilation of marine energy management measures.
https://youtu.be/fyxiAxi95s8
(Place below Interactions)

**Comment by geocoug** [comment]
Minor revision on the [faq page](https://marineenergy.app/faq.html). Shift TOC over to the right a bit so there is some padding on the left side.
