### ISSUE TITLE
Update wording around Regulations intro text wrt "NWP 52"

### ISSUE THREAD

**Issue by bbest** [mhk-env/mhk-env.github.io#9]
From: [MHK Toolkit notes_DOE.docx - Google Docs](https://docs.google.com/document/d/1yNnqEyZOBQdxYDTB0vDMymtitwW4YHRv/edit):

## Regulation – ACOE Led processes

The Corps currently prefers “USACE” over “ACOE”. Please make that change wherever needed.
Recommend changing the wording in the description paragraph “regardless of whether the project is grid-connected or not, unless the project activities fall within the scope of Nationwide Permit 52 ” This makes it sound like ACOE is not involved in the NWP 52.
In the NWP 52 link, can you reference what page the relevant info starts on?  Otherwise you have to sift through 149 pages or do control F for NWP 52.  Also is there a more succinct reference that clearly outlines what can be covered by a NWP52?  With the inclusion of all the “multiple commenters noted…” I find the format of that document to be confusing and difficult to tease out exactly what the NWP encompasses.

**Comment by bbest** [comment]
Hi @rupertsmudge,

Can you please check suggested wording below to see if that makes more sense?

Current wording in doe-revs branch:

> Projects in state waters require authorization from the U.S. Army Corps of Engineers (USACE) regardless of whether the project is grid-connected or not, unless the project activities fall within the scope of [Nationwide Permit 52](https://www.govinfo.gov/content/pkg/FR-2017-01-06/pdf/2016-31355.pdf) (Water-Based Renewable Energy Generation Pilot Projects, Effective Date: March 19, 2017; Expiration Date: March 18, 2022). Authorization from the USACE encompasses the following regulatory elements:

p. 72 of PDF: NWP 52. Water-Based Renewable Energy Generation Pilot Projects. 

> Projects ... not. See further definitions and requirements in [Nationwide Permit 52](https://www.govinfo.gov/content/pkg/FR-2017-01-06/pdf/2016-31355.pdf) (p. 73-74; ...

Or can we better summarize this per the request?

> Also is there a more succinct reference that clearly outlines what can be covered by a NWP52? With the inclusion of all the “multiple commenters noted…” I find the format of that document to be confusing and difficult to tease out exactly what the NWP encompasses.

**Comment by rupertsmudge** [comment]
Good question. Unfortunately, not my area of expertise. I suggest you email your question to Zach, with cc to Paul Jacobsen and Sharon. -G

**Comment by bbest** [comment]
Migrated text from USACE to ACOE
